apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      initContainers:
        - name: prisma-migrate
          image: ghcr.io/haianhltr/timeclock:19e67ce891584c75a7431c2e8372cc9020814af4-migrator
      containers:
        - name: frontend
          image: ghcr.io/haianhltr/timeclock:19e67ce891584c75a7431c2e8372cc9020814af4
          env:
            - name: NEXTAUTH_URL
              value: "https://clockin.randomstuffs.org"
