apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      initContainers:
        - name: prisma-migrate
          image: ghcr.io/haianhltr/timeclock:8b08e55792ec635f6c6c3e41bc4bd0388b4766f2-migrator
      containers:
        - name: frontend
          image: ghcr.io/haianhltr/timeclock:8b08e55792ec635f6c6c3e41bc4bd0388b4766f2
          env:
            - name: NEXTAUTH_URL
              value: "https://clockin.randomstuffs.org"
