apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      initContainers:
        - name: prisma-migrate
          image: ghcr.io/haianhltr/timeclock:b5111204c293ad20a45f00e19b101e9a321d30d8-migrator
      containers:
        - name: frontend
          image: ghcr.io/haianhltr/timeclock:b5111204c293ad20a45f00e19b101e9a321d30d8
          env:
            - name: NEXTAUTH_URL
              value: "https://clockin.randomstuffs.org"
