apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: timeclock
  POSTGRES_PASSWORD: t1m3cl0ck-pr0d-2026
  POSTGRES_DB: timeclock
  DATABASE_URL: postgresql://timeclock:t1m3cl0ck-pr0d-2026@postgres:5432/timeclock
